# Generated by Django 2.1.15 on 2021-04-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Requestor', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('StartDate', models.CharField(max_length=100)),
                ('Impact', models.CharField(max_length=100)),
                ('DueDate', models.CharField(max_length=100)),
                ('Scope', models.CharField(max_length=100)),
                ('Notes', models.CharField(max_length=100)),
                ('ProposedChange', models.CharField(max_length=100)),
                ('Reson', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('ActionPlan', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('createdDate', models.CharField(max_length=100)),
            ],
        ),
    ]
