# Generated by Django 3.2 on 2021-04-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_requestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=100)),
                ('createdDate', models.CharField(max_length=100)),
                ('Assignee', models.CharField(max_length=100)),
            ],
        ),
    ]
